
//AUTH
export const IS_LOGIN = "IS_LOGIN";
export const IS_REGISTER = "IS_REGISTER";
export const AUTH_IS_OPEN = "AUTH_IS_OPEN";
export const AUTH_IS_CLOSE = "AUTH_IS_CLOSE";
export const UPDATE_USER_CREDENTIALS = "UPDATE_USER_CREDENTIALS";

//MENU
export const MENU_IS_OPEN = "MENU_IS_OPEN";
export const MENU_IS_CLOSE = "MENU_IS_OPEN";

//CART
export const CART_IS_OPEN = "CART_IS_OPEN";
export const CART_IS_CLOSE = "CART_IS_OPEN";
export const CHANGE_COUNT_PRODUCTS = "CHANGE_COUNT_PRODUCTS";
export const SET_PRODUCTS_ID = "SET_PRODUCTS_ID";
